nodeLinker: node-modules

packageExtensions:
  "@terra-money/wallet-provider@3.11.1":
    peerDependencies:
      "@terra-money/terra.js": ^3.1.6
  eslint-config-react-app@7.0.1:
    peerDependencies:
      "@babel/plugin-syntax-flow": ^7.14.5
      "@babel/plugin-transform-react-jsx": ^7.14.9
  react-scripts@5.0.1:
    peerDependencies:
      "@babel/plugin-syntax-flow": ^7.14.5
      "@babel/plugin-transform-react-jsx": ^7.14.9

  "@walletconnect/heartbeat@1.2.0":
    peerDependencies:
      "@types/node": "*"
      "typescript": ">=2.7"
    dependencies:
      "@types/node": "*"

  "@walletconnect/core@2.4.7":
    peerDependencies:
      "@types/node": "*"
      "typescript": ">=2.7"

  "@walletconnect/sign-client@2.4.7":
    peerDependencies:
      "@types/node": "*"
      "typescript": ">=2.7"

  "@walletconnect/types@2.4.7":
    peerDependencies:
      "@types/node": "*"
      "typescript": ">=2.7"

  "@walletconnect/utils@2.4.7":
    peerDependencies:
      "@types/node": "*"
      "typescript": ">=2.7"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
